In [1]:
import codecs
sentences_file = codecs.open('sentences.txt', 'r', encoding = 'utf8')

In [2]:
import numpy as np
sentences = np.array([])
for line in sentences_file:
    sentences = np.append(sentences, line.lower().strip())
sentences_file.close()

In [3]:
import re

d = {}
i = 0

for row in sentences:
    words = re.split('[^a-z]*', row)
    for word in words:
        if(word != ''):
            if((word in d.keys()) == False):
                d.update({word: i})
                i += 1
        else:
            continue

In [4]:
matrix = np.zeros((len(sentences), len(d)))
print matrix.shape

(22L, 254L)


In [5]:
from collections import Counter
i = 0
for row in sentences:
    words = re.split('[^a-z]*', row)
    for word in words:
        if((word in d.keys()) != False):
            c = words.count(word)
            j = d.get(word)
            matrix[i][j] = c
    i += 1
print matrix

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]


In [6]:
from scipy.spatial import distance

In [38]:
result = {}
i = 1
while i < 22:
    c = distance.cosine(matrix[0], matrix[i])
    result.update({i: c})
    
    i += 1

In [39]:
minimum = min([x for x in result.values()])
k = result.keys()[result.values().index(minimum)]
del result[k]

s = "%s%s" % (minimum, ' ')

minimum = min([x for x in result.values()])
k = result.keys()[result.values().index(minimum)]

s = "%s%s" % (s, minimum,)

print s 

0.7327387580875756 0.7770887149698589


In [40]:
result_file = open('w2t1_Klepikov_Egor.txt', 'w')
result_file.write(s)
result_file.close()